### ISSUE TITLE
Implement transactions list page

### ISSUE THREAD

**Issue by celadari** [kwickbit/kwickbit_frontend_v0#16]
Implement transactions list page.

Use static list of transactions for now: define a static list of json as your sources GET service.
each transaction has several features:
- from, to, date, ...
- published status
- additional data (like a metadata field): where you can put contract address for non native tokens. Contract address in tooltip like in the screenshot

OUT of the scope of this feature (NOT TO BE DONE FOR THIS FEATURE):
- ~sources message "No transactions yet, please add source" when empty~
- ~specific transaction view in more detail~
- ~alert about specif non setted currencies~

Colors
Light blue of logo: #39BFF0
Dark blue of logo: #21254E
Green color for button and status: #4ADDB6

![image](https://github.com/kwickbit/kwickbit_frontend_v0/assets/17705729/cb88aba1-3e92-4cd6-a354-2f3215da8958)

**Comment by geniusFulldev** [comment]
![image](https://github.com/kwickbit/kwickbit_frontend_v0/assets/140017305/154c9723-bfbd-4762-81e2-c364446d3281)
Are these components Select elements or sort?

**Comment by celadari** [comment]
They are select elements.

If you have time (only IF it does not add too much additional workload) for sort elements you can do it on date & Time column header.

**Comment by geniusFulldev** [comment]
How should I build the select elements?  I don't see any design for them

**Comment by celadari** [comment]
This is not in the scope of this task.
Please read the task and perform tasks sequentially

**Comment by geniusFulldev** [comment]
I got it
